### PR TITLE
add bedtime lullaby

### PR DESCRIPTION
**Pull request by Nilsu11**
A try for making a sleep timer. It is easier to let one try than explaining it.
For short: I tried to add the google clock sleep timer at first, but ended up deleting the activity.

Also merging my old fork made a mess, in reality there just are a few changes to some files. In April should be the first commit which truly matters.

### CODE REVIEW

**Comment by BlackyHawky** [comment]
I don't doubt that your proposal is interesting, but I'm really sorry, your PR is a bit of a mess... 73 commits for a single modification request is way too much to analyze especially since most of the commits concern my own modifications mixed with yours.

Please, update your main branch from mine or even clone the project again; create a new branch from your main branch dedicated to you modification and repropose your PR.

Let me remind you again: one PR = one modification, just to make things clearer.

In any case, I'll give it a try in the next days, as I'm very interested in improving the bedtime mode.

**Comment by Nilsu11** [comment]
Yes, this time I did it. As I mentioned at the beginning ifyou look at the changed files you can see, that they don't correspond the 73 commits.

Anyway it still is just a draft and not ready for review jet. I just wanted to have one so I don't forget to fix stuff and since I didn't want to trouble you I left this pull request as a draft.

Just for the future, I open draft pull request relatively early when my feature clearly isn't structured and WIP.

Also DO NOT JET give it a try since this is still WIP and will stay so till at least next Sunday. I will message you if I think it is in at least beta stage and the sleeptimer itself works reliable (I noticed now it is still up to chance).

**Comment by BlackyHawky** [comment]
OK ok. Take your time working on it and thanks for working on it.

Let me know when I can start testing.

If you can, take the opportunity to make a new PR without all those useless commits appearing.
I won't be making any more changes for a while unless someone reports a major problem with the application.

**Comment by Nilsu11** [comment]
I (somehow) can't stop the service when timed (the notification can) and don't know how to. I'll leave this to someone else and provide my work as base. Also I notice, that one jet can't decide the length of the sleep timer. to do this copy the code from the other spinner and adapt it.

**Comment by Nilsu11** [comment]
@BlackyHawky  think I now fixed the issue I wrote of. I will now resolve the conflicts and start developing the clock app again. This is just a side note but I also laid the ground work for media alarm with this in a more viewable way (the com.best.music package).

Best regards and thanks for still developing this app

**Pull request closed without merging**
